export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { RefreshAccessToken, Login, GetAllUsers, CreateUser, UpdateUser, GetCategories, CreateCategory, UpdateCategory, DeleteCategory, GetTemplateByCategory, SaveTemplate, GetTemplateById, DeleteTemplate, GetTemplateHeaders, CreateTemplateHeader, UpdateTemplateHeader, DeleteTemplateHeader, GetTypeOptions, GetTypeOptionsPaged, CreateTypeOptionTable, CreateTypeOptionType, UpdateTypeOptionType, DeleteTypeOptionType, GetTypeOptionValues, CreateTypeOptionValue, UpdateTypeOptionValue, DeleteTypeOptionValue, LoginPayload, AuthTokenData, LoginResponse, RefreshTokenPayload, RefreshTokenResponse, AuthUser, CategoryItem, GetAllUsersResponse, GetCategoriesResponse, CategoryPayload, CreateUserPayload, UpdateUserPayload, AuthActionResponse, TemplateHeaderNode, TemplateHeaderParent, TemplateByCategoryData, TemplateByCategoryResponse, SaveTemplatePayload, SaveTemplateResponse, TemplateHeaderNodePayload, TypeOptionTypeItem, TypeOptionValueItem, TypeOptionPagedResponse, TypeOptionActionResponse } from '../app/composables/AuthApi';
export { GetDynamicFormHeaderDepartments, GetDynamicFormHeaders, CreateDynamicFormHeader, UpdateDynamicFormHeader, DeleteDynamicFormHeader, DynamicFormHeaderItem, DynamicFormHeaderDepartment, DynamicFormHeaderPayload } from '../app/composables/DynamicFormHeaderApi';
export { GetNdTruoc, UpdateTichTruocND, GetCVK2, UpdateCVK2, GetNdBaoDuong, UpdateTichBaoDuongND, GetCVK4, NoteCVK4, NoteCVK6, ExportPdf, UpdateTichCVK, GetNdSau, TichNdSau, GetCVK6 } from '../app/composables/FORMMAINApi';
export { GetFirstForm, FirstFormResponse, FirstFormData } from '../app/composables/FirstFormApi';
export { GetWODataListORA, GetListSelect, SavePersonTable, UpdateGhiChuR5 } from '../app/composables/GhiChuKienNghi';
export { NdTruocItem, NdTruocData, NdTruocResponse } from '../app/composables/NDCV';
export { GetAllOpenForms, CreateOpenForm, UpdateOpenForm, DeleteOpenForm, OpenFormItem, OpenFormCreateRequest, OpenFormUpdateRequest, OpenFormResponse, OpenFormPagedData, OpenFormPagedResponse, OpenFormSingleResponse, OpenFormDeleteResponse } from '../app/composables/OpenFormApi';
export { GetNguoiChoPhep, GetPersonList, UpdateNguoiChoPhep, LoadPersonV2, GetPersonSelectList, UpdatePersonWithTruongNhom, UpdatePersonWithVHTB, UpdatePersonWithBDTB, UpdatePersonWithTruongCongTrinh, GetTruongCongTrinh, NguoiChoPhepItem, NguoiChoPhepResponse, WOPersonData, GetWODataListORAResponse, PersonSelectData, GetListSelectResponse } from '../app/composables/PersonApi';
export { PersonData, PersonResponse } from '../app/composables/PersonTable';
export { GetAllTTLVTB, UpdateTTLVTB, GetDesignerByWo, UpdateTTLVTBRow, TTLVTBItem, TTLVTBResponse, TTLVTBUpdateRequest, TTLVTBUpdateResponse, TTLVTBCreateRequest, TTLVTBCreateResponse, DesignerTemplateNode, DesignerTemplateParent, DesignerTemplate, TTLVTBDesignerGroup, TTLVTBUdfFieldConfig, TTLVTBFieldStyleConfig, TTLVTBDesignerData, TTLVTBDesignerResponse, TTLVTBUpdateRowResponse } from '../app/composables/TTLVTBApi';
export { UpdateWoInfoTinhTrangTbiR5, GetTGNL, UpdateTGNL, TGNLItem, TGNLGetResponse, TGNLUpdateResponse } from '../app/composables/TinhTrangThietBiApi';
export { GetToolByWO, AddTool, DeleteTool, GetToolsPaged, SearchTools, GetAllTools, ToolData, ToolResponse } from '../app/composables/ToolApi';
export { getPartsByWO, deletePartWO, createPartWO, updatePartIssue, updatePartReturn, GetVatTuTieuHaoByWO, GetAllPart, UpdatePart, VatTuTieuHaoWOItem, PartApiResult, VatTuTieuHaoItem, VatTuTieuHaoResponse, VatTuPartItem, VatTuPartResponse, UpdatePartItem, UpdatePartResponse } from '../app/composables/VatTuTieuHaoWOApi';
export { useApi } from '../app/composables/useApi';
export { useDebounce } from '../app/composables/useDebounce';
export { useNuxtDevTools } from '../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';